[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "multiclip"
version = "2.2.0"
description = "The Arsenal"
dependencies = [
    "keyboard",
    "pyperclip",
    "pyautogui",
    "pynput",
    "plyer"
]

[tool.setuptools.packages.find]
where = ["."]
