/* automatically generated from settings-dialog.ui */
#ifdef __SUNPRO_C
#pragma align 4 (settings_dialog_ui)
#endif
#ifdef __GNUC__
static const char settings_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char settings_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.14\"/><requires lib=\"libxfce4ui-2\" version=\"4.12\"/"
  "><object class=\"GtkAdjustment\" id=\"adjustment1\"><property name=\"lo"
  "wer\">5</property><property name=\"upper\">1000</property><property nam"
  "e=\"value\">5</property><property name=\"step_increment\">5</property><"
  "property name=\"page_increment\">10</property></object><object class=\""
  "GtkAdjustment\" id=\"adjustment2\"><property name=\"upper\">100</proper"
  "ty><property name=\"step_increment\">1</property><property name=\"page_"
  "increment\">10</property></object><object class=\"GtkImage\" id=\"image"
  "5\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"icon_name\">help-browser</property"
  "></object><object class=\"GtkImage\" id=\"image6\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><pro"
  "perty name=\"icon_name\">window-close-symbolic</property></object><obje"
  "ct class=\"XfceTitledDialog\" id=\"settings-dialog\"><property name=\"c"
  "an_focus\">False</property><property name=\"title\" translatable=\"yes\""
  ">Clipman Settings</property><property name=\"window_position\">center</"
  "property><property name=\"default_width\">340</property><property name="
  "\"default_height\">390</property><property name=\"destroy_with_parent\""
  ">True</property><property name=\"icon_name\">xfce4-clipman-plugin</prop"
  "erty><property name=\"type_hint\">dialog</property><child internal-chil"
  "d=\"vbox\"><object class=\"GtkBox\" id=\"settings-dialog-vbox\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property><property name=\"orientation\">vertical</property><property na"
  "me=\"spacing\">2</property><child internal-child=\"action_area\"><objec"
  "t class=\"GtkButtonBox\" id=\"settings-dialog-actionarea\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><child><object class=\"GtkButton\" id=\"settings-dialog-button-help"
  "\"><property name=\"label\" translatable=\"yes\">_Help</property><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">True</"
  "property><property name=\"receives_default\">True</property><property n"
  "ame=\"image\">image5</property><property name=\"use_underline\">True</p"
  "roperty></object><packing><property name=\"expand\">False</property><pr"
  "operty name=\"fill\">False</property><property name=\"position\">0</pro"
  "perty><property name=\"secondary\">True</property></packing></child><ch"
  "ild><object class=\"GtkButton\" id=\"settings-dialog-button-close\"><pr"
  "operty name=\"label\" translatable=\"yes\">_Close</property><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">True</prope"
  "rty><property name=\"receives_default\">True</property><property name=\""
  "image\">image6</property><property name=\"use_underline\">True</propert"
  "y></object><packing><property name=\"expand\">False</property><property"
  " name=\"fill\">False</property><property name=\"position\">1</property>"
  "</packing></child></object><packing><property name=\"expand\">False</pr"
  "operty><property name=\"fill\">False</property><property name=\"positio"
  "n\">0</property></packing></child><child><object class=\"GtkNotebook\" "
  "id=\"settings-dialog-notebook\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">True</property><property name=\"border_"
  "width\">6</property><child><object class=\"GtkBox\" id=\"vbox-general\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"border_width\">12</property><property"
  " name=\"orientation\">vertical</property><property name=\"spacing\">18<"
  "/property><child><object class=\"GtkFrame\" id=\"frame-behavior\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"label_xalign\">0</property><property name=\""
  "shadow_type\">none</property><child><object class=\"GtkAlignment\" id=\""
  "alignment-behavior\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"top_padding\">6</"
  "property><property name=\"left_padding\">12</property><child><object cl"
  "ass=\"GtkBox\" id=\"vbox-behavior\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"or"
  "ientation\">vertical</property><property name=\"spacing\">6</property><"
  "child><object class=\"GtkCheckButton\" id=\"add-selections\"><property "
  "name=\"label\" translatable=\"yes\">Sync mouse _selections</property><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Tr"
  "ue</property><property name=\"receives_default\">False</property><prope"
  "rty name=\"has_tooltip\">True</property><property name=\"tooltip_text\""
  " translatable=\"yes\">If checked, selections will be synced with the de"
  "fault clipboard, so you can paste what you select with Ctrl-V. Converse"
  "ly, manual copies will be synced with the primary clipboard, so you can"
  " paste what you copy with middle-click.</property><property name=\"use_"
  "underline\">True</property><property name=\"draw_indicator\">True</prop"
  "erty></object><packing><property name=\"expand\">False</property><prope"
  "rty name=\"fill\">True</property><property name=\"position\">0</propert"
  "y></packing></child><child><object class=\"GtkCheckButton\" id=\"persis"
  "tent-selections\"><property name=\"label\" translatable=\"yes\">_Persis"
  "t mouse selections</property><property name=\"visible\" bind-source=\"a"
  "dd-selections\" bind-property=\"active\" bind-flags=\"G_BINDING_INVERT_"
  "BOOLEAN | G_BINDING_SYNC_CREATE\"/><property name=\"can_focus\">True</p"
  "roperty><property name=\"receives_default\">False</property><property n"
  "ame=\"has_tooltip\">True</property><property name=\"tooltip_text\" tran"
  "slatable=\"yes\">If checked, the primary clipboard (middle-click paste)"
  " will persist until next selection if current selection is lost (e.g. b"
  "y left-clicking anywhere in a text area)</property><property name=\"use"
  "_underline\">True</property><property name=\"draw_indicator\">True</pro"
  "perty></object><packing><property name=\"expand\">False</property><prop"
  "erty name=\"fill\">True</property><property name=\"position\">1</proper"
  "ty></packing></child><child><object class=\"GtkCheckButton\" id=\"show-"
  "qr-code\"><property name=\"label\" translatable=\"yes\">_QR-Code suppor"
  "t</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">False</p"
  "roperty><property name=\"has_tooltip\">True</property><property name=\""
  "tooltip_text\" translatable=\"yes\">If checked, the menu shows a QR-Cod"
  "e of the currently selected clipboard entry</property><property name=\""
  "use_underline\">True</property><property name=\"draw_indicator\">True</"
  "property></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">True</property><property name=\"position\">2</pro"
  "perty></packing></child><child><object class=\"GtkBox\" id=\"hbox1\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"tooltip_text\" translatable=\"yes\">Auto"
  "matically paste a selected item from the history</property><property na"
  "me=\"spacing\">4</property><child><object class=\"GtkLabel\" id=\"label"
  "-paste-on-activate\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"label\" translata"
  "ble=\"yes\">_Paste instantly:</property><property name=\"use_underline\""
  ">True</property><property name=\"mnemonic_widget\">combobox-paste-on-ac"
  "tivate</property><property name=\"xalign\">0</property></object><packin"
  "g><property name=\"expand\">False</property><property name=\"fill\">Fal"
  "se</property><property name=\"position\">0</property></packing></child>"
  "<child><object class=\"GtkComboBoxText\" id=\"combobox-paste-on-activat"
  "e\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property></object><packing><property name=\"expand\">False</"
  "property><property name=\"fill\">True</property><property name=\"pack_t"
  "ype\">end</property><property name=\"position\">1</property></packing><"
  "/child></object><packing><property name=\"expand\">False</property><pro"
  "perty name=\"fill\">False</property><property name=\"position\">3</prop"
  "erty></packing></child></object></child></object></child><child type=\""
  "label\"><object class=\"GtkLabel\" id=\"label-general\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">False</property"
  "><property name=\"label\" translatable=\"yes\">&lt;b&gt;General&lt;/b&g"
  "t;</property><property name=\"use_markup\">True</property></object></ch"
  "ild></object><packing><property name=\"expand\">False</property><proper"
  "ty name=\"fill\">False</property><property name=\"position\">0</propert"
  "y></packing></child><child><object class=\"GtkFrame\" id=\"frame-histor"
  "y\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"label_xalign\">0</property><proper"
  "ty name=\"shadow_type\">none</property><child><object class=\"GtkAlignm"
  "ent\" id=\"alignment-history\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"top_pad"
  "ding\">6</property><property name=\"left_padding\">12</property><child>"
  "<object class=\"GtkBox\" id=\"vbox-history\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"orientation\">vertical</property><property name=\"spacing\">6</p"
  "roperty><child><object class=\"GtkCheckButton\" id=\"popup-at-pointer\""
  "><property name=\"label\" translatable=\"yes\">P_osition menu at mouse "
  "pointer</property><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">True</property><property name=\"receives_default\">Fa"
  "lse</property><property name=\"tooltip_text\" translatable=\"yes\">Popu"
  "p the menu at the mouse pointer position: especially useful for the xfc"
  "e4-popup-clipman command</property><property name=\"use_underline\">Tru"
  "e</property><property name=\"draw_indicator\">True</property></object><"
  "packing><property name=\"expand\">False</property><property name=\"fill"
  "\">False</property><property name=\"position\">0</property></packing></"
  "child><child><object class=\"GtkBox\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><child><object cl"
  "ass=\"GtkLabel\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><property name=\"label\" translatable="
  "\"yes\">Maximum items:</property><property name=\"xalign\">0</property>"
  "</object><packing><property name=\"expand\">False</property><property n"
  "ame=\"fill\">True</property><property name=\"position\">0</property></p"
  "acking></child><child><object class=\"GtkSpinButton\" id=\"max-menu-ite"
  "ms\"><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">True</property><property name=\"adjustment\">adjustment2</property"
  "></object><packing><property name=\"expand\">False</property><property "
  "name=\"fill\">True</property><property name=\"pack_type\">end</property"
  "><property name=\"position\">1</property></packing></child></object><pa"
  "cking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">1</property></packing></chi"
  "ld></object></child></object></child><child type=\"label\"><object clas"
  "s=\"GtkLabel\" id=\"label-menu\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"label"
  "\" translatable=\"yes\">&lt;b&gt;Menu&lt;/b&gt;</property><property nam"
  "e=\"use_markup\">True</property></object></child></object><packing><pro"
  "perty name=\"expand\">False</property><property name=\"fill\">False</pr"
  "operty><property name=\"position\">1</property></packing></child></obje"
  "ct></child><child type=\"tab\"><object class=\"GtkLabel\" id=\"label-be"
  "havior\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"label\" translatable=\"yes\">"
  "_Behavior</property><property name=\"use_underline\">True</property></o"
  "bject><packing><property name=\"tab_fill\">False</property></packing></"
  "child><child><object class=\"GtkBox\" id=\"vbox-actions\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"border_width\">12</property><property name=\"orient"
  "ation\">vertical</property><property name=\"spacing\">6</property><chil"
  "d><object class=\"GtkBox\" id=\"box1\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><child><object c"
  "lass=\"GtkLabel\" id=\"label1\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"label\""
  " translatable=\"yes\">&lt;b&gt;_Enable automatic actions&lt;/b&gt;</pro"
  "perty><property name=\"use_markup\">True</property><property name=\"use"
  "_underline\">True</property><property name=\"xalign\">0</property></obj"
  "ect><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">0</property></packing"
  "></child><child><object class=\"GtkSwitch\" id=\"enable-actions\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">True<"
  "/property><property name=\"tooltip_text\" translatable=\"yes\">If check"
  "ed, the clipboard texts will be matched against regular expressions and"
  " a menu will display possible actions automatically.\nOtherwise the men"
  "u will only appear when calling \"xfce4-popup-clipman-actions\" (and a "
  "match was found)</property></object><packing><property name=\"expand\">"
  "False</property><property name=\"fill\">True</property><property name=\""
  "position\">1</property></packing></child></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">True</property><p"
  "roperty name=\"position\">0</property></packing></child><child><object "
  "class=\"GtkBox\" id=\"box-actions\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"ma"
  "rgin_left\">12</property><property name=\"orientation\">vertical</prope"
  "rty><child><object class=\"GtkBox\" id=\"hbox-skip-action\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"tooltip_text\" translatable=\"yes\">When the sele"
  "ction is done and the Control key is still pressed down, the popup menu"
  " for matched actions will be shown or hidden</property><property name=\""
  "spacing\">4</property><child><object class=\"GtkLabel\" id=\"label-skip"
  "-action\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">False</property><property name=\"label\" translatable=\"yes\""
  ">_Pressing Ctrl during selection:</property><property name=\"use_underl"
  "ine\">True</property><property name=\"mnemonic_widget\">combobox-skip-a"
  "ction</property><property name=\"xalign\">0</property></object><packing"
  "><property name=\"expand\">False</property><property name=\"fill\">Fals"
  "e</property><property name=\"position\">0</property></packing></child><"
  "child><object class=\"GtkComboBoxText\" id=\"combobox-skip-action\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property></object><packing><property name=\"expand\">True</property"
  "><property name=\"fill\">True</property><property name=\"position\">1</"
  "property></packing></child></object><packing><property name=\"expand\">"
  "False</property><property name=\"fill\">False</property><property name="
  "\"position\">0</property></packing></child><child><object class=\"GtkBo"
  "x\" id=\"hbox2\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><property name=\"margin_top\">12</prop"
  "erty><property name=\"spacing\">6</property><child><object class=\"GtkS"
  "crolledWindow\" id=\"scrolledwindow1\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">True</property><property name=\""
  "shadow_type\">in</property><child><object class=\"GtkTreeView\" id=\"ac"
  "tions\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">True</property><property name=\"headers_visible\">False</proper"
  "ty><property name=\"rules_hint\">True</property><child internal-child=\""
  "selection\"><object class=\"GtkTreeSelection\" id=\"treeview-selection1"
  "\"/></child></object></child></object><packing><property name=\"expand\""
  ">True</property><property name=\"fill\">True</property><property name=\""
  "position\">0</property></packing></child><child><object class=\"GtkBox\""
  " id=\"vbox4\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"orientation\">vertical</"
  "property><property name=\"spacing\">6</property><child><object class=\""
  "GtkButton\" id=\"button-add-action\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">True</property><property name=\"re"
  "ceives_default\">True</property><property name=\"tooltip_text\" transla"
  "table=\"yes\">Add action</property><child><object class=\"GtkImage\" id"
  "=\"image1\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"icon_name\">list-add-symbo"
  "lic</property><property name=\"icon_size\">1</property></object></child"
  "></object><packing><property name=\"expand\">False</property><property "
  "name=\"fill\">False</property><property name=\"position\">0</property><"
  "/packing></child><child><object class=\"GtkButton\" id=\"button-edit-ac"
  "tion\"><property name=\"visible\">True</property><property name=\"sensi"
  "tive\">False</property><property name=\"can_focus\">True</property><pro"
  "perty name=\"receives_default\">True</property><property name=\"tooltip"
  "_text\" translatable=\"yes\">Edit action</property><child><object class"
  "=\"GtkImage\" id=\"image2\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"icon_name\""
  ">document-edit-symbolic</property><property name=\"icon_size\">1</prope"
  "rty></object></child></object><packing><property name=\"expand\">False<"
  "/property><property name=\"fill\">False</property><property name=\"posi"
  "tion\">1</property></packing></child><child><object class=\"GtkButton\""
  " id=\"button-delete-action\"><property name=\"visible\">True</property>"
  "<property name=\"sensitive\">False</property><property name=\"can_focus"
  "\">True</property><property name=\"receives_default\">True</property><p"
  "roperty name=\"tooltip_text\" translatable=\"yes\">Delete action</prope"
  "rty><child><object class=\"GtkImage\" id=\"image3\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"icon_name\">edit-delete-symbolic</property><property name"
  "=\"icon_size\">1</property></object></child></object><packing><property"
  " name=\"expand\">False</property><property name=\"fill\">False</propert"
  "y><property name=\"position\">2</property></packing></child><child><obj"
  "ect class=\"GtkButton\" id=\"button-reset-actions\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">True</property><pro"
  "perty name=\"receives_default\">True</property><property name=\"tooltip"
  "_text\" translatable=\"yes\">Reset all actions to the system default va"
  "lues</property><child><object class=\"GtkImage\" id=\"image4\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"icon_name\">edit-clear-symbolic</property><pro"
  "perty name=\"icon_size\">1</property></object></child></object><packing"
  "><property name=\"expand\">False</property><property name=\"fill\">Fals"
  "e</property><property name=\"pack_type\">end</property><property name=\""
  "position\">3</property></packing></child></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">False</property><"
  "property name=\"position\">1</property></packing></child></object><pack"
  "ing><property name=\"expand\">True</property><property name=\"fill\">Tr"
  "ue</property><property name=\"position\">1</property></packing></child>"
  "</object><packing><property name=\"expand\">False</property><property n"
  "ame=\"fill\">True</property><property name=\"position\">1</property></p"
  "acking></child></object><packing><property name=\"position\">1</propert"
  "y></packing></child><child type=\"tab\"><object class=\"GtkLabel\" id=\""
  "label-actions\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"label\" translatable=\""
  "yes\">_Actions</property><property name=\"use_underline\">True</propert"
  "y></object><packing><property name=\"position\">1</property><property n"
  "ame=\"tab_fill\">False</property></packing></child><child><object class"
  "=\"GtkBox\" id=\"vbox-tweaks\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"border_"
  "width\">12</property><property name=\"orientation\">vertical</property>"
  "<property name=\"spacing\">6</property><child><object class=\"GtkBox\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><child><object class=\"GtkLabel\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"label\" translatable=\"yes\">&lt;b&gt;Remember history&lt;/"
  "b&gt;</property><property name=\"use_markup\">True</property><property "
  "name=\"xalign\">0</property></object><packing><property name=\"expand\""
  ">True</property><property name=\"fill\">True</property><property name=\""
  "position\">0</property></packing></child><child><object class=\"GtkSwit"
  "ch\" id=\"save-on-quit\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">True</property></object><packing><property nam"
  "e=\"expand\">False</property><property name=\"fill\">True</property><pr"
  "operty name=\"position\">1</property></packing></child></object><packin"
  "g><property name=\"expand\">False</property><property name=\"fill\">Tru"
  "e</property><property name=\"position\">0</property></packing></child><"
  "child><object class=\"GtkBox\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"margin_"
  "left\">12</property><property name=\"orientation\">vertical</property><"
  "property name=\"spacing\">6</property><child><object class=\"GtkCheckBu"
  "tton\" id=\"store-an-image\"><property name=\"label\" translatable=\"ye"
  "s\">Remember last copied _image</property><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">True</property><property name"
  "=\"receives_default\">False</property><property name=\"tooltip_text\" t"
  "ranslatable=\"yes\">If checked, this option allows one to store one ima"
  "ge inside the history</property><property name=\"use_underline\">True</"
  "property><property name=\"draw_indicator\">True</property></object><pac"
  "king><property name=\"expand\">False</property><property name=\"fill\">"
  "True</property><property name=\"position\">0</property></packing></chil"
  "d><child><object class=\"GtkCheckButton\" id=\"reorder-items\"><propert"
  "y name=\"label\" translatable=\"yes\">_Reorder history items</property>"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "True</property><property name=\"receives_default\">False</property><pro"
  "perty name=\"tooltip_text\" translatable=\"yes\">Push last copied text "
  "to the top of the history, useful to reorder old items</property><prope"
  "rty name=\"use_underline\">True</property><property name=\"draw_indicat"
  "or\">True</property></object><packing><property name=\"expand\">False</"
  "property><property name=\"fill\">False</property><property name=\"posit"
  "ion\">1</property></packing></child><child><object class=\"GtkCheckButt"
  "on\" id=\"reverse-order\"><property name=\"label\" translatable=\"yes\""
  ">Re_verse history order</property><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">True</property><property name=\"recei"
  "ves_default\">False</property><property name=\"tooltip_text\" translata"
  "ble=\"yes\">Reverse order of the history shown in the menu</property><p"
  "roperty name=\"use_underline\">True</property><property name=\"draw_ind"
  "icator\">True</property></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">False</property><property name=\"p"
  "osition\">2</property></packing></child><child><object class=\"GtkCheck"
  "Button\" id=\"history-ignore-selections\"><property name=\"label\" tran"
  "slatable=\"yes\">Ignore mouse s_elections</property><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">True</property><pro"
  "perty name=\"receives_default\">False</property><property name=\"has_to"
  "oltip\">True</property><property name=\"tooltip_text\" translatable=\"y"
  "es\">If checked, the selections won\'t affect the history except the ma"
  "nual copies</property><property name=\"use_underline\">True</property><"
  "property name=\"draw_indicator\">True</property></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">True</prop"
  "erty><property name=\"position\">3</property></packing></child><child><"
  "object class=\"GtkBox\" id=\"hbox-history-size\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"spacing\">4</property><child><object class=\"GtkLabel\" id=\""
  "label-history-size\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"label\" translata"
  "ble=\"yes\">Size of the _history:</property><property name=\"use_underl"
  "ine\">True</property><property name=\"mnemonic_widget\">max-texts-in-hi"
  "story</property><property name=\"xalign\">0</property></object><packing"
  "><property name=\"expand\">False</property><property name=\"fill\">Fals"
  "e</property><property name=\"position\">0</property></packing></child><"
  "child><object class=\"GtkSpinButton\" id=\"max-texts-in-history\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">True<"
  "/property><property name=\"invisible_char\">\342\200\242</property><pro"
  "perty name=\"text\" translatable=\"yes\">5</property><property name=\"a"
  "djustment\">adjustment1</property><property name=\"value\">100</propert"
  "y></object><packing><property name=\"expand\">False</property><property"
  " name=\"fill\">True</property><property name=\"pack_type\">end</propert"
  "y><property name=\"position\">1</property></packing></child></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">4</property></packing></chi"
  "ld></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">True</property><property name=\"position\">6</property>"
  "</packing></child></object><packing><property name=\"position\">2</prop"
  "erty></packing></child><child type=\"tab\"><object class=\"GtkLabel\" i"
  "d=\"label-histor\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"label\" translatabl"
  "e=\"yes\">H_istory</property><property name=\"use_underline\">True</pro"
  "perty></object><packing><property name=\"position\">2</property><proper"
  "ty name=\"tab_fill\">False</property></packing></child></object><packin"
  "g><property name=\"expand\">True</property><property name=\"fill\">True"
  "</property><property name=\"position\">1</property></packing></child></"
  "object></child><action-widgets><action-widget response=\"2\">settings-d"
  "ialog-button-help</action-widget><action-widget response=\"0\">settings"
  "-dialog-button-close</action-widget></action-widgets></object><object c"
  "lass=\"GtkDialog\" id=\"action-dialog\"><property name=\"can_focus\">Fa"
  "lse</property><property name=\"title\" translatable=\"yes\">Edit Action"
  "</property><property name=\"modal\">True</property><property name=\"win"
  "dow_position\">center-on-parent</property><property name=\"default_widt"
  "h\">400</property><property name=\"default_height\">440</property><prop"
  "erty name=\"destroy_with_parent\">True</property><property name=\"icon_"
  "name\">system-run</property><property name=\"type_hint\">dialog</proper"
  "ty><property name=\"skip_taskbar_hint\">True</property><property name=\""
  "transient_for\">settings-dialog</property><child><placeholder/></child>"
  "<child internal-child=\"vbox\"><object class=\"GtkBox\" id=\"action-dia"
  "log-vbox\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"orientation\">vertical</pro"
  "perty><property name=\"spacing\">6</property><child internal-child=\"ac"
  "tion_area\"><object class=\"GtkButtonBox\" id=\"action-dialog-actionare"
  "a\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"layout_style\">end</property><chil"
  "d><object class=\"GtkButton\" id=\"action-dialog-button-cancel\"><prope"
  "rty name=\"label\" translatable=\"yes\">_Cancel</property><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">True</propert"
  "y><property name=\"receives_default\">True</property><property name=\"u"
  "se_underline\">True</property></object><packing><property name=\"expand"
  "\">False</property><property name=\"fill\">False</property><property na"
  "me=\"position\">0</property></packing></child><child><object class=\"Gt"
  "kButton\" id=\"action-dialog-button-ok\"><property name=\"label\" trans"
  "latable=\"yes\">_OK</property><property name=\"visible\">True</property"
  "><property name=\"can_focus\">True</property><property name=\"receives_"
  "default\">True</property><property name=\"use_underline\">True</propert"
  "y></object><packing><property name=\"expand\">False</property><property"
  " name=\"fill\">False</property><property name=\"position\">1</property>"
  "</packing></child></object><packing><property name=\"expand\">False</pr"
  "operty><property name=\"fill\">False</property><property name=\"pack_ty"
  "pe\">end</property><property name=\"position\">0</property></packing></"
  "child><child><object class=\"GtkBox\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "border_width\">6</property><property name=\"orientation\">vertical</pro"
  "perty><property name=\"spacing\">18</property><child><object class=\"Gt"
  "kFrame\" id=\"frame-action\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"label_xal"
  "ign\">0</property><property name=\"shadow_type\">none</property><child>"
  "<object class=\"GtkAlignment\" id=\"alignment-action\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"top_padding\">6</property><property name=\"left_padding"
  "\">12</property><child><object class=\"GtkBox\" id=\"box2\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"orientation\">vertical</property><property name=\""
  "spacing\">6</property><child><object class=\"GtkGrid\" id=\"grid1\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property><property name=\"row_spacing\">6</property><property name="
  "\"column_spacing\">12</property><property name=\"row_homogeneous\">True"
  "</property><child><object class=\"GtkEntry\" id=\"action-name\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">True</p"
  "roperty><property name=\"hexpand\">True</property><property name=\"invi"
  "sible_char\">\342\200\242</property></object><packing><property name=\""
  "left_attach\">1</property><property name=\"top_attach\">0</property><pr"
  "operty name=\"width\">2</property></packing></child><child><object clas"
  "s=\"GtkLabel\" id=\"label-action-name\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"label\" translatable=\"yes\">Name:</property><property name=\"xalign\""
  ">0</property></object><packing><property name=\"left_attach\">0</proper"
  "ty><property name=\"top_attach\">0</property></packing></child><child><"
  "object class=\"GtkLabel\" id=\"label-action-pattern\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label\" translatable=\"yes\">Pattern:</property><proper"
  "ty name=\"xalign\">0</property></object><packing><property name=\"left_"
  "attach\">0</property><property name=\"top_attach\">1</property></packin"
  "g></child><child><object class=\"GtkEntry\" id=\"regex\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">True</property"
  "><property name=\"hexpand\">True</property><property name=\"invisible_c"
  "har\">\342\200\242</property></object><packing><property name=\"left_at"
  "tach\">1</property><property name=\"top_attach\">1</property></packing>"
  "</child><child><object class=\"GtkButton\" id=\"button-action-pattern\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"receives_default\">True</property><pro"
  "perty name=\"halign\">center</property><child><object class=\"GtkImage\""
  " id=\"image-action-pattern\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"icon_name"
  "\">document-edit-symbolic</property><property name=\"icon_size\">1</pro"
  "perty></object></child></object><packing><property name=\"left_attach\""
  ">2</property><property name=\"top_attach\">1</property></packing></chil"
  "d></object><packing><property name=\"expand\">False</property><property"
  " name=\"fill\">False</property><property name=\"position\">0</property>"
  "</packing></child><child><object class=\"GtkInfoBar\" id=\"regex-infoba"
  "r\"><property name=\"can_focus\">False</property><property name=\"revea"
  "led\">False</property><child internal-child=\"action_area\"><object cla"
  "ss=\"GtkButtonBox\"><property name=\"can_focus\">False</property><prope"
  "rty name=\"spacing\">6</property><property name=\"layout_style\">end</p"
  "roperty><child><placeholder/></child></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">False</property><prope"
  "rty name=\"position\">0</property></packing></child><child internal-chi"
  "ld=\"content_area\"><object class=\"GtkBox\"><property name=\"can_focus"
  "\">False</property><property name=\"spacing\">16</property><child><obje"
  "ct class=\"GtkImage\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><property name=\"icon_name\">dial"
  "og-information-symbolic</property><property name=\"icon_size\">3</prope"
  "rty></object><packing><property name=\"expand\">False</property><proper"
  "ty name=\"fill\">True</property><property name=\"position\">0</property"
  "></packing></child><child><object class=\"GtkLabel\" id=\"label-regex-i"
  "nfo\"><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">False</property><property name=\"label\" translatable=\"yes\">You"
  " can use the substitution parameters \"\\1\", \"\\2\" and so on in the "
  "commands. The parameter \"\\0\" represents the complete text. The patte"
  "rn is always anchored within the special characters ^$</property><prope"
  "rty name=\"wrap\">True</property><property name=\"xalign\">0</property>"
  "</object><packing><property name=\"expand\">True</property><property na"
  "me=\"fill\">True</property><property name=\"position\">2</property></pa"
  "cking></child></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"fill\">False</property><property name=\"position\">"
  "0</property></packing></child></object><packing><property name=\"expand"
  "\">True</property><property name=\"fill\">True</property><property name"
  "=\"position\">1</property></packing></child><child><object class=\"GtkC"
  "heckButton\" id=\"manual\"><property name=\"label\" translatable=\"yes\""
  ">Activate on manual copy instead of selection</property><property name="
  "\"visible\">True</property><property name=\"can_focus\">True</property>"
  "<property name=\"receives_default\">False</property><property name=\"ha"
  "s_tooltip\">True</property><property name=\"tooltip_text\" translatable"
  "=\"yes\">By default the action is triggered by a selection: check this "
  "option to trigger the action when you make a manual copy instead. Note "
  "that in this case, the Control key no longer has any effect.</property>"
  "<property name=\"draw_indicator\">True</property></object><packing><pro"
  "perty name=\"expand\">False</property><property name=\"fill\">True</pro"
  "perty><property name=\"position\">2</property></packing></child></objec"
  "t></child></object></child><child type=\"label\"><object class=\"GtkLab"
  "el\" id=\"label-action\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"label\" trans"
  "latable=\"yes\">&lt;b&gt;Action&lt;/b&gt;</property><property name=\"us"
  "e_markup\">True</property></object></child></object><packing><property "
  "name=\"expand\">False</property><property name=\"fill\">False</property"
  "><property name=\"position\">1</property></packing></child><child><obje"
  "ct class=\"GtkFrame\" id=\"frame-commands\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"label_xalign\">0</property><property name=\"shadow_type\">none</p"
  "roperty><child><object class=\"GtkAlignment\" id=\"alignment-commands\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"top_padding\">6</property><property n"
  "ame=\"left_padding\">12</property><child><object class=\"GtkBox\" id=\""
  "hbox-commands\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"spacing\">6</property>"
  "<child><object class=\"GtkBox\" id=\"vbox-commands\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"orientation\">vertical</property><property name=\"spacin"
  "g\">6</property><child><object class=\"GtkGrid\" id=\"grid2\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"row_spacing\">6</property><property name=\"colu"
  "mn_spacing\">6</property><property name=\"row_homogeneous\">True</prope"
  "rty><child><object class=\"GtkEntry\" id=\"command-name\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">True</propert"
  "y><property name=\"hexpand\">True</property><property name=\"invisible_"
  "char\">\342\200\242</property></object><packing><property name=\"left_a"
  "ttach\">1</property><property name=\"top_attach\">0</property></packing"
  "></child><child><object class=\"GtkEntry\" id=\"command\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">True</propert"
  "y><property name=\"hexpand\">True</property><property name=\"invisible_"
  "char\">\342\200\242</property></object><packing><property name=\"left_a"
  "ttach\">1</property><property name=\"top_attach\">1</property></packing"
  "></child><child><object class=\"GtkLabel\" id=\"label-command\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property><property name=\"label\" translatable=\"yes\">Command:</proper"
  "ty><property name=\"xalign\">0</property></object><packing><property na"
  "me=\"left_attach\">0</property><property name=\"top_attach\">1</propert"
  "y></packing></child><child><object class=\"GtkLabel\" id=\"label-comman"
  "d-name\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"label\" translatable=\"yes\">"
  "Name:</property><property name=\"xalign\">0</property></object><packing"
  "><property name=\"left_attach\">0</property><property name=\"top_attach"
  "\">0</property></packing></child></object><packing><property name=\"exp"
  "and\">False</property><property name=\"fill\">False</property><property"
  " name=\"position\">0</property></packing></child><child><object class=\""
  "GtkScrolledWindow\" id=\"scrolledwindow-commands\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">True</property><prop"
  "erty name=\"shadow_type\">in</property><child><object class=\"GtkTreeVi"
  "ew\" id=\"commands\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">True</property><property name=\"hexpand\">True</pr"
  "operty><property name=\"headers_visible\">False</property><property nam"
  "e=\"rules_hint\">True</property><child internal-child=\"selection\"><ob"
  "ject class=\"GtkTreeSelection\"/></child></object></child></object><pac"
  "king><property name=\"expand\">True</property><property name=\"fill\">T"
  "rue</property><property name=\"position\">2</property></packing></child"
  "></object><packing><property name=\"expand\">True</property><property n"
  "ame=\"fill\">True</property><property name=\"position\">0</property></p"
  "acking></child><child><object class=\"GtkBox\" id=\"vbox-command-button"
  "s\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"orientation\">vertical</property><"
  "property name=\"spacing\">6</property><child><object class=\"GtkButton\""
  " id=\"button-add-command\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">True</property><property name=\"receives_def"
  "ault\">True</property><child><object class=\"GtkImage\" id=\"image-add-"
  "command\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">False</property><property name=\"icon_name\">list-add-symboli"
  "c</property><property name=\"icon_size\">1</property></object></child><"
  "/object><packing><property name=\"expand\">False</property><property na"
  "me=\"fill\">False</property><property name=\"position\">0</property></p"
  "acking></child><child><object class=\"GtkButton\" id=\"button-refresh-c"
  "ommand\"><property name=\"visible\">True</property><property name=\"sen"
  "sitive\">False</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">True</property><child><object class=\""
  "GtkImage\" id=\"image-refresh-command\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"icon_name\">document-save-symbolic</property><property name=\"icon_si"
  "ze\">1</property></object></child></object><packing><property name=\"ex"
  "pand\">False</property><property name=\"fill\">False</property><propert"
  "y name=\"position\">1</property></packing></child><child><object class="
  "\"GtkButton\" id=\"button-delete-command\"><property name=\"visible\">T"
  "rue</property><property name=\"sensitive\">False</property><property na"
  "me=\"can_focus\">True</property><property name=\"receives_default\">Tru"
  "e</property><child><object class=\"GtkImage\" id=\"image-delete-command"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"icon_name\">edit-delete-symbolic</p"
  "roperty><property name=\"icon_size\">1</property></object></child></obj"
  "ect><packing><property name=\"expand\">False</property><property name=\""
  "fill\">False</property><property name=\"position\">2</property></packin"
  "g></child></object><packing><property name=\"expand\">False</property><"
  "property name=\"fill\">False</property><property name=\"position\">1</p"
  "roperty></packing></child></object></child></object></child><child type"
  "=\"label\"><object class=\"GtkLabel\" id=\"label-commands\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"label\" translatable=\"yes\">&lt;b&gt;Commands&lt"
  ";/b&gt;</property><property name=\"use_markup\">True</property></object"
  "></child></object><packing><property name=\"expand\">True</property><pr"
  "operty name=\"fill\">True</property><property name=\"position\">2</prop"
  "erty></packing></child></object><packing><property name=\"expand\">True"
  "</property><property name=\"fill\">True</property><property name=\"posi"
  "tion\">1</property></packing></child></object></child><action-widgets><"
  "action-widget response=\"0\">action-dialog-button-cancel</action-widget"
  "><action-widget response=\"1\">action-dialog-button-ok</action-widget><"
  "/action-widgets></object><object class=\"GtkTextBuffer\" id=\"textbuffe"
  "r1\"><property name=\"text\" translatable=\"yes\">Type here your custom"
  " text, for example a URL, a filename, etc.</property></object><object c"
  "lass=\"GtkDialog\" id=\"regex-dialog\"><property name=\"can_focus\">Fal"
  "se</property><property name=\"title\" translatable=\"yes\">Regular expr"
  "ession</property><property name=\"modal\">True</property><property name"
  "=\"default_width\">260</property><property name=\"default_height\">260<"
  "/property><property name=\"destroy_with_parent\">True</property><proper"
  "ty name=\"icon_name\">gtk-edit</property><property name=\"type_hint\">d"
  "ialog</property><property name=\"skip_taskbar_hint\">True</property><pr"
  "operty name=\"transient_for\">action-dialog</property><child><placehold"
  "er/></child><child internal-child=\"vbox\"><object class=\"GtkBox\" id="
  "\"regex-dialog-vbox\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><property name=\"orientation\">ve"
  "rtical</property><property name=\"spacing\">2</property><child internal"
  "-child=\"action_area\"><object class=\"GtkButtonBox\" id=\"regex-dialog"
  "-actionarea\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"layout_style\">end</prop"
  "erty><child><object class=\"GtkButton\" id=\"regex-dialog-button-cancel"
  "\"><property name=\"label\" translatable=\"yes\">_Cancel</property><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">True"
  "</property><property name=\"receives_default\">True</property><property"
  " name=\"use_underline\">True</property></object><packing><property name"
  "=\"expand\">False</property><property name=\"fill\">False</property><pr"
  "operty name=\"position\">0</property></packing></child><child><object c"
  "lass=\"GtkButton\" id=\"regex-dialog-button-ok\"><property name=\"label"
  "\" translatable=\"yes\">_OK</property><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"r"
  "eceives_default\">True</property><property name=\"use_underline\">True<"
  "/property></object><packing><property name=\"expand\">False</property><"
  "property name=\"fill\">False</property><property name=\"position\">1</p"
  "roperty></packing></child></object><packing><property name=\"expand\">F"
  "alse</property><property name=\"fill\">False</property><property name=\""
  "pack_type\">end</property><property name=\"position\">0</property></pac"
  "king></child><child><object class=\"GtkBox\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"border_width\">6</property><property name=\"orientation\">vertic"
  "al</property><property name=\"spacing\">6</property><child><object clas"
  "s=\"GtkEntry\" id=\"regex-entry\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">True</property><property name=\"invis"
  "ible_char\">\342\200\242</property><property name=\"secondary_icon_stoc"
  "k\">gtk-apply</property></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">0</property></packing></child><child><object class=\"GtkScroll"
  "edWindow\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">True</property><property name=\"shadow_type\">in</property><"
  "child><object class=\"GtkViewport\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><child><object clas"
  "s=\"GtkTextView\" id=\"regex-textview\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">True</property><property name=\""
  "pixels_above_lines\">2</property><property name=\"pixels_below_lines\">"
  "2</property><property name=\"pixels_inside_wrap\">4</property><property"
  " name=\"wrap_mode\">word</property><property name=\"buffer\">textbuffer"
  "1</property></object></child></object></child></object><packing><proper"
  "ty name=\"expand\">True</property><property name=\"fill\">True</propert"
  "y><property name=\"position\">1</property></packing></child></object><p"
  "acking><property name=\"expand\">True</property><property name=\"fill\""
  ">True</property><property name=\"position\">1</property></packing></chi"
  "ld></object></child><action-widgets><action-widget response=\"-6\">rege"
  "x-dialog-button-cancel</action-widget><action-widget response=\"-10\">r"
  "egex-dialog-button-ok</action-widget></action-widgets></object></interf"
  "ace>"
};

static const unsigned settings_dialog_ui_length = 45068u;

